name: Code Quality Checks

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check TypeScript
      run: npx tsc --noEmit
      
    - name: Run ESLint
      run: npx eslint src --ext .ts,.tsx --max-warnings 0 || true
      
    - name: Check formatting with Prettier
      run: npx prettier --check "src/**/*.{ts,tsx,js,jsx,json,css,md}" || true
      
    - name: Test coverage report
      run: npm run test:coverage
      
    - name: Comment Test Coverage
      uses: 5monkeys/cobertura-action@master
      if: github.event_name == 'pull_request'
      with:
        path: coverage/cobertura-coverage.xml
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        minimum_coverage: 60
        fail_below_threshold: false
